# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: "3"
vars:
  BRANCH: 3.0.1
  BASEVER: "{{.BRANCH}}-beta"
  VERSION:
    sh: git describe --tags --abbrev=0 2>/dev/null || git rev-parse --short HEAD
  S: ""
  DEBUG: ""

tasks:
  default:
    - task: build

  cli-ver:
    - git tag -d $(git tag)
    - git tag -f {{.BASEVER}}.$(date +%y%m%d%H%M){{.S}}
    - git tag

  setup: { silent:true }

  build:
    desc: build nuv locally
    cmds:
      - go build {{.DEBUG}} -ldflags "-X main.NuvVersion={{.VERSION}} -X main.NuvBranch={{.BRANCH}}"  -o bin/nuv
    sources:
      - "*.go"
      - "tools/*.go"
    generates:
      - bin/nuv

  debug:
    cmds:
      - task: build
        vars:
          DEBUG: "-gcflags '-l -N'"
      - dlv exec ./bin/nuv -- {{.CLI_ARGS}}

  install:
    desc: install nuv using a local folder for binaries
    deps:
      - build
    dir: bin
    cmds:
      - ./nuv getall
      - sudo rm -f /usr/bin/nuv /usr/local/bin/nuv
      - sudo ln -sf $PWD/{{OS}}/{{ARCH}}/nuv /usr/local/bin/nuv
      - sudo ln -sf $PWD/{{OS}}/{{ARCH}}/nuv /usr/bin/nuv

  test:
    desc: tests all
    cmds:
      - curl -sL https://raw.githubusercontent.com/nuvolaris/olaris/{{.BRANCH}}/runtimes.json >runtimes.json
      - task: install
      - task: utest
      - task: itest

  utest:
    desc: unit test nuv
    cmds:
      - rm -Rf ~/.nuv/olaris
      - go test ./...

  itest:
    desc: integration tests nuv
    dir: tests
    cmds:
      - rm -Rf ~/.nuv/olaris
      - bats/bin/bats .

  clean:
    - rm -f bin/nuv
    - go clean -cache -modcache

  rebuild:
    - rm -f bin/nuv
    - task: build

  utestdiff:
    cmds:
      - |-
        if test -z '{{.N}}'
        then  go test -v | tee _difftest
              python3 difftest.py
        else  python3 difftest.py {{.N}}
        fi

  old-sync-task:
    - |
      cd tools/sh
      git fetch --all
      git checkout origin/nuvolaris -B nuvolaris
      go get github.com/nuvolaris/nuv@latest
      git commit -m "updated go mod" -a
      git push origin nuvolaris
      cd ../task
      git fetch --all
      git checkout origin/nuvolaris -B nuvolaris
      go get github.com/nuvolaris/sh/v3@nuvolaris
      git commit -m "updated go mod" -a
      git push origin nuvolaris
      cd ..
      go get github.com/nuvolaris/task/v3@nuvolaris
      git commit -m "updated go mod" -a
      git push origin main


  sync-wsk:
    - |
      NOW=$(date +%y%m%d%H%M)
      cd tools/openwhisk-wskdeploy
      git tag -d $(git tag)
      git commit -m $NOW -a
      git tag v0.0.0.$NOW
      git push origin nuvolaris --tags
      cd ../openwhisk-cli
      git tag -d $(git tag)
      go get github.com/nuvolaris/openwhisk-wskdeploy@v0.0.0.$NOW
      git commit -m $NOW -a
      git tag v0.0.0.$NOW
      git push origin nuvolaris --tags
      cd ../..
      go get github.com/nuvolaris/openwhisk-cli@v0.0.0.$NOW



